config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :poems
  resources :stories

  root "authors#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :poems, dependent: :destroy
  has_many :author_taggings, dependent: :destroy
  has_many :tags, through: :author_taggings, dependent: :destroy


  # Seperates text in single words and compares them to the list
  # of predefined keywords which result in an array of the keywords
  # that are present in the text
  def self.tagging(text)
    text_array = text.scan(/\w+/).map(&:downcase)
    tags_array = Tag.pluck(:name)
    tags_array & text_array
  end
end

app/models/author_tagging.rb
class AuthorTagging < ActiveRecord::Base
  belongs_to :author
  belongs_to :tag
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  belongs_to :author
  has_many :poem_taggings, dependent: :destroy
  has_many :tags, through: :poem_taggings, dependent: :destroy

  # Seperates text in single words and compares them to the list
  # of predefined keywords which result in an array of the keywords
  # that are present in the text
  def self.tagging(text)
    text_array = text.scan(/\w+/).map(&:downcase)
    tags_array = Tag.pluck(:name)
    tags_array & text_array
  end

end

app/models/poem_tagging.rb
class PoemTagging < ActiveRecord::Base
  belongs_to :poem
  belongs_to :tag
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :author
  has_many :story_taggings, dependent: :destroy
  has_many :tags, through: :story_taggings, dependent: :destroy

  # Seperates text in single words and compares them to the list
  # of predefined keywords which result in an array of the keywords
  # that are present in the text
  def self.tagging(text)
    text_array = text.scan(/\w+/).map(&:downcase)
    tags_array = Tag.pluck(:name)
    tags_array & text_array
  end
end

app/models/story_tagging.rb
class StoryTagging < ActiveRecord::Base
  belongs_to :story
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :authors_taggings
  has_many :authors, through: :author_taggings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all.sort_by { |author| author.name }
  end

  def show
    @author = Author.find( params[:id] )
  end


  def new
    @author = Author.new
  end

  def create
    @author = Author.new( author_params )

    # Stored found keywords in variable @tags
    @tags = Author.tagging(@author.bio)

    if @author.save
      # Iterates through the @tags array and for every tag
      # Creates a record in the join table with author_id and tag_id
      @tags.each do |tag_name|
        if tag = Tag.find_by( name: tag_name )
          AuthorTagging.create( author: @author, tag: tag )
        end
      end
      redirect_to @author
    else
      render 'new'
    end
  end

  def destroy
    @author = Author.find( params[:id] )

    @author.destroy

    redirect_to authors_path
  end

  private

    def author_params
      params.require( :author ).permit( :name, :bio )
    end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

  def index
    @poems = Poem.all.sort_by { |poem| poem.title }
  end

  def show
    @poem = Poem.find( params[:id] )
  end

  def new
    @poem = Poem.new
    @poem.author_id = params[:author_id]
  end

  def create
    @poem = Poem.new( poem_params )
    @tags = Poem.tagging( @poem.content )

    if @poem.save
      # Iterates through the @tags array and for every tag
      # Creates a record in the join table with poem_id and tag_id
      @tags.each do |tag_name|
        if tag = Tag.find_by( name: tag_name )
          PoemTagging.create( poem: @poem, tag: tag )
        end
      end
      redirect_to poems_path
    else
      render 'new'
    end
  end

  def destroy
    @poem = Poem.find( params[:id] )
    author_id = @poem.author_id
    @poem.destroy
    redirect_to author_path( author_id )
  end

  private

    def poem_params
      params.require( :poem ).permit( :title, :content, :metaphor, :date,
                                                                   :author_id )
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all.sort_by { |story| story.title }
  end

  def show
    @story = Story.find( params[:id] )
  end

  def new
    @story = Story.new
    @story.author_id = params[:author_id]
  end

  def create
    @story = Story.new( story_params )
    @tags = Story.tagging( @story.content )

    if @story.save
      # Iterates through the @tags array and for every tag
      # Creates a record in the join table with story_id and tag_id
      @tags.each do |tag_name|
        if tag = Tag.find_by( name: tag_name )
          StoryTagging.create( story: @story, tag: tag )
        end
      end
      redirect_to stories_path
    else
      render 'new'
    end
  end

  def destroy
    @story = Story.find( params[:id] )
    author_id = @story.author_id
    @story.destroy
    redirect_to author_path( author_id )
  end

  private

    def story_params
      params.require( :story ).permit( :title, :content, :description, :date,
                                       :author_id )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <ul class="field_with_errors">
    <% @author.errors.full_messages.each do |msg| %>
      <li class="field_with_errors"><%= msg %></li>
    <% end %>
  </ul>

    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
       <%= f.label :bio %>
       <%= f.text_area :bio, class: "form-control", rows: 10  %>
    </div>

    <%= f.submit (@author.new_record? ? "Create" : "Update"),
                  class: "form-control btn-primary" %>

<% end %>

app/views/authors/index.html.erb
<h1>List of all the authors</h1>

<% @authors.each do |author| %>
    <p><%= link_to author.name, author %></p>
<% end %>

<%= link_to 'Add new author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render "form" %>

app/views/authors/show.html.erb
<h4>
  <%= @author.name %>
  <%= link_to "Delete", author_path( @author ),
      method: :delete,
      data: { confirm: "Are you sure?" },
      class: "btn btn-default" %>
</h4>
<%= simple_format @author.bio %>

<% @author.tags.each do |tag| %>
  <div class="chip tags z-depth-2"><%= tag.name %></div>
<% end %>

<hr  />

<%= link_to "Add new Poem", new_poem_path( author_id: @author.id),
                                           class: "btn btn-default" %>

<%= link_to "Add new Story", new_story_path( author_id: @author.id),
                                           class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoryTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'shared/header' %>

<%= yield %>

</body>
</html>

app/views/poems/_form.html.erb
<%= form_for @poem do |f| %>

  <ul class="field_with_errors">
    <% @poem.errors.full_messages.each do |msg| %>
      <li class="field_with_errors"><%= msg %></li>
    <% end %>
  </ul>

  <%= f.hidden_field :author_id, :value => @poem.author.id %>

  <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
     <%= f.label :content %>
     <%= f.text_area :content, class: "form-control", rows: 10  %>
  </div>

  <div class="form-group">
     <%= f.label :metaphor %>
     <%= f.text_field :metaphor, class: "form-control" %>
  </div>

  <div class="form-group">
     <%= f.label :date %>
     <%= f.datetime_select :date, class: "form-control" %>
  </div>

  <%= f.submit (@poem.new_record? ? "Create" : "Update"),
                class: "form-control btn-primary" %>

<% end %>

app/views/poems/index.html.erb
<h1>List of all the Poems</h1>

<% @poems.each do |poem| %>
  <div class="all_overview">
    <p>
      <%= link_to poem.title, poem %>
      (Methaphor: <%= poem.metaphor %> - Author: <%=link_to poem.author.name,
                                                    poem.author %>)
      <% poem.tags.each do |tag| %>
        <div class="chip tags z-depth-2"><%= tag.name %></div>
      <% end %>
    </p>
    <hr  />
  </div>

<% end %>

app/views/poems/new.html.erb
<h1>New poem by <%= @poem.author.name %></h1>

<%= render "form" %>

app/views/poems/show.html.erb
<h4>
  <%= @poem.title %> by <%= @poem.author.name %>
  <%= link_to "Delete", poem_path( @poem ),
      method: :delete,
      data: { confirm: "Are you sure?" },
      class: "btn btn-default" %>
</h4>
<%= simple_format @poem.content %>

<hr />

<div style="font-style: italic;">
  <%= @poem.metaphor %>
</div>

Tags:
<% @poem.tags.each do |tag| %>
  <div class="chip tags z-depth-2"><%= tag.name %></div>
<% end %>

app/views/shared/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <ul style="font-size: 1.4em">
      <li class="left" style="cursor: pointer; font-size: 1.1em;">
        <%= link_to "Home", root_path %>
      </li>
      <li class="brand-logo center">StoryTime</li>

      <li class="right">
        <%= link_to "Stories", stories_path %>
      </li>
      <li class="right">
        <%= link_to "Poems", poems_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>

  <ul class="field_with_errors">
    <% @story.errors.full_messages.each do |msg| %>
      <li class="field_with_errors"><%= msg %></li>
    <% end %>
  </ul>

  <%= f.hidden_field :author_id, :value => @story.author.id %>

  <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
     <%= f.label :content %>
     <%= f.text_area :content, class: "form-control", rows: 10  %>
  </div>

  <div class="form-group">
     <%= f.label :description %>
     <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
     <%= f.label :date %>
     <%= f.datetime_select :date, class: "form-control" %>
  </div>

  <%= f.submit (@story.new_record? ? "Create" : "Update"),
                class: "form-control btn-primary" %>

<% end %>

app/views/stories/index.html.erb
<h1>List of all the Stories</h1>

<% @stories.each do |story| %>
  <div class="all_overview">
    <p>
      <%= link_to story.title, story %>
      (Description: <%= story.description %> - Author:
      <%= link_to story.author.name, story.author %>)

      <% story.tags.each do |tag| %>
        <div class="chip tags z-depth-2"><%= tag.name %></div>
      <% end %>
    </p>
  </div>
<% end %>

app/views/stories/new.html.erb
<h1>New Short Story by <%= @story.author.name %></h1>

<%= render "form" %>

app/views/stories/show.html.erb
<h4>
  <%= @story.title %> by <%= @story.author.name %>
  <%= link_to "Delete", story_path( @story ),
      method: :delete,
      data: { confirm: "Are you sure?" },
      class: "btn btn-default" %>
</h4>
<%= simple_format @story.content %>
<hr />
<div style="font-style: italic;">
  <%= @story.description %>
</div>


Tags:
<% @story.tags.each do |tag| %>
  <div class="chip tags z-depth-2"><%= tag.name %></div>
<% end %>